FROM golang:1.19-alpine

# Set working directory
WORKDIR /go/src/target

# Run tests
CMD CGO_ENABLED=0 DATABASE_URL=postgresql://root:root@db/go-example-db?sslmode=disable PORT=:80 go test --tags=integration ./...